# Generated by Django 5.0.4 on 2024-04-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_calculatetype_remove_quote_origin_quote_origin_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='destination',
        ),
        migrations.AddField(
            model_name='quote',
            name='destination_city',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Destination City'),
        ),
        migrations.AddField(
            model_name='quote',
            name='destination_country',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Destination Country'),
        ),
    ]
