# Generated by Django 5.0.4 on 2024-04-18 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_quote_sum_buy_filelds_alter_quote_total_total_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='sum_buy_filelds',
            new_name='sum_buy_fields',
        ),
    ]
