# Generated by Django 5.0.4 on 2024-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_rename_sum_buy_filelds_quote_sum_buy_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceexcludes',
            options={'verbose_name': 'Services excludes', 'verbose_name_plural': 'Services excludes'},
        ),
        migrations.AlterModelOptions(
            name='serviceincludes',
            options={'verbose_name': 'Service inclues', 'verbose_name_plural': 'Services includes'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='freight_mode',
            field=models.CharField(blank=True, choices=[('Air', 'Air'), ('LCL', 'LCL'), ("FCL 20'ft", "FCL 20'ft"), ("FCL 40'ft", "FCL 40'ft"), ("FCL 40'HC", "FCL 40'HC")], max_length=125, null=True, verbose_name='Freight mode'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='service_type',
            field=models.CharField(blank=True, choices=[('Door to Door', 'Door to Door'), ('Door to Port', 'Door to Port'), ('Port to Door', 'Port to Door'), ('Port to Port', 'Port to Port')], default='Door to Door', max_length=125, null=True, verbose_name='Service type'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Volume'),
        ),
    ]
