# Generated by Django 5.0.4 on 2024-04-21 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_alter_serviceexcludes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency', to='quotes.currencies', verbose_name='Currencies'),
        ),
    ]
