# Generated by Django 5.0.4 on 2024-04-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_quote_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='item_id',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Item id'),
        ),
    ]
