# Generated by Django 5.0.4 on 2024-04-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0009_quote_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Quotation number'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='transit_time',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Transit time'),
        ),
    ]
